services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: ./src/Dockerfile
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - '8080:8080'
  frontend:
    container_name: frontend
    build:
      context: ./ui
      dockerfile: ./Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./ui:/app/client
      - '/app/client/node_modules'
    depends_on:
      - backend
  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
